### ISSUE TITLE
Cannot encode "ÄÖÜ"

### ISSUE THREAD

**Issue by Erbsenklemmer** [Hackaroth/QRCODE#2]
If I put "ÄÜÖ" to param-Data it is encoded correctly.
`Data    = "ÄÖÜß Hello";`
QrCode will bei decoded als "<some strange chars>\+ Hello".

**Comment by Hackaroth** [comment]
Hi Erbsenklemmer

If encode the string "ÄÖÜß Hello" o other combination like  "ÄÖÜ Hello", "ÄÖÜ"  the qr code is correctly decoded so i cannot reproduce the problem. Please report how to reprocude the problem.

Thanks for your report

**Comment by Erbsenklemmer** [comment]
Thank for the fast reply.
How have you defined The `Data` in `struct params`?
Greetings.

**Comment by Hackaroth** [comment]
Hi

Not diretly in the source code but with the executable.
./QRCODE -d "ÄÖÜß Hello"

I attach the output bitmap. When i decode it the result is the same string that i had encoded.

[out.bmp.tar.gz](https://github.com/Hackaroth/QRCODE/files/139879/out.bmp.tar.gz)

regards

**Comment by Erbsenklemmer** [comment]
Hi,
Your Ouput looks fine and in works. -> Thanks
I'm using VS2010 and I need a dynamic creation of the QrCode. You defined the Data from the command line, but I want to push it dynamicaly to the QrController. Something like `params.Data = _T("ÄÖÜ");`
I can send you my VisualStudio-solution-files if are interested.
regards.

**Comment by Hackaroth** [comment]
Hi

I'm sorry but i work under linux and don't use VS. 

I've made a simple test in the main.cpp and the output file looks fine.

```
int main(int argc, char* argv[])
{
    show_license();

    params p;
    p.Data = "ÄÖÜß Hello";

    QRController* controller = new QRController(p.Data, p.ECL, p.Width, p.Height, p.Version);
    controller->SaveToFile(p.of);

    delete controller;
    return 0;
}

```

Hope this can help you.

regards

**Comment by Erbsenklemmer** [comment]
Hi,
I think it's my mistake and my Project isn't configurred well, because this line of code throws and compiler error:
`p.Data = "ÄÖÜß Hello";`
I will check that and inform you again.

Thank a Long
regards

**Comment by Erbsenklemmer** [comment]
Hi,
I done it.
The string mit be a mulibyte-string. When I use this conversion it works:

```
   // Convert a wide Unicode string to an UTF8 string
    std::string utf8_encode(const std::wstring &wstr)
    {
        if( wstr.empty() ) 
            return std::string();

        int size_needed = WideCharToMultiByte(CP_UTF8, 0, &wstr[0], (int)wstr.size(), NULL, 0, NULL, NULL);
        std::string strTo( size_needed, 0 );
        WideCharToMultiByte                  (CP_UTF8, 0, &wstr[0], (int)wstr.size(), &strTo[0], size_needed, NULL, NULL);
        return strTo;
    }
```

Assign it to the Data member:
`Data = utf8_encode(L"ÄÖÜß @€");`

That's it.
I have closes the issue.
Many thanks for your help.
Regards.

**Comment by Hackaroth** [comment]
You welcome Erbsenklemmer.
I'm really glad that you have solved.

take care!
Best Ragards
